version: '3.5'
# start DOCKER  C:\Java\account-service> docker-compose up -d

services:
  db:
    container_name: postgres_container
    image: postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mymail.ru
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

  firefox:
    image: selenium/standalone-firefox
    hostname: firefox
    privileged: true
    shm_size: 2gb
    container_name: selenium-firefox
    ports:
      - "4445:4444"
      - "7900:7900"
    networks:
      - postgres

  data-scrapper:
    image: simakoff/data-scrapper:latest
    container_name: data-scrapper
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8082:8082"
    depends_on:
      - firefox
    networks:
      - postgres

#  telegram-bot:
#    image: simakoff/telegram-bot:latest
#    container_name: telegram-bot
#    ports:
#      - "8083:8083"
#    networks:
#      - postgres
#    depends_on:
#      - data-scrapper

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
